# Site settings
title: Evan R. Rees
email: erees@wisc.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "wiscevan.github.io" # the base hostname & protocol for your site

twitter_username: TweetlessEvan
github_username: WiscEvan
linkedin_username: evanroyrees
# Build settings
markdown: kramdown
